#!/usr/bin/env python3
"""
Regenerates BrinaOSAiName, the overlay that renames OPPO AI to BrinaAI.

Why it needs generating rather than hand-writing: an RRO does not win by being
an overlay, it wins by being the best configuration match. UMS ships every one
of these strings in ~75 locales, so on an en-GB phone the target's own `en-rGB`
value beats an overlay that only carries a default one, and the row keeps
saying "OPPO AI". The overlay therefore has to repeat itself in every locale the
target defines - which is what this script does, reading the locale list out of
UMS.apk so it stays right when the target changes.

    python3 devices/common/rro/tools/mkai.py     # run from the toolkit root
"""
import os, re, shutil, subprocess

AAPT = 'otatools/bin/aapt2'
APK = 'build/portrom/images/my_stock/priv-app/UMS/UMS.apk'
OUT = 'devices/common/rro/BrinaOSAiName/res'

# setting_name_* is the row in the Settings list, ai_setting_header_title* the
# title of the page it opens, ai_setting_header_subtitle* the tagline under it.
# UMS picks between the oppo/oneplus/next variants at runtime from the brand the
# build reports, so all of them are renamed - a port that ends up reporting
# oneplus or realme would otherwise slip through with the stock name.
NAME = 'BrinaAI'
TAGLINE = "Your Short n' Sweet AI"
STRINGS = [
    ('setting_name_oppo_ai', NAME),
    ('setting_name_oneplus_ai', NAME),
    ('setting_name_next_ai', NAME),
    ('ai_setting_header_title', NAME),
    ('ai_setting_header_title_2', NAME),
    ('ai_setting_header_title_3', NAME),
    ('ai_setting_header_subtitle', TAGLINE),
    ('ai_setting_header_subtitle_2', TAGLINE),
    ('ai_setting_header_subtitle_oneplus', TAGLINE),
]

HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by devices/common/rro/tools/mkai.py - do not hand edit.
     One copy per locale UMS defines, because a target's localised string beats
     an overlay's default one. -->
<resources>
'''


def configs():
    """Every configuration the renamed strings appear in, '' for the default."""
    want = {n for n, _ in STRINGS}
    out, cur = set(), None
    dump = subprocess.run([AAPT, 'dump', 'resources', APK],
                          capture_output=True, text=True).stdout
    for line in dump.splitlines():
        m = re.match(r'\s+resource 0x[0-9a-f]+ (\w+)/([A-Za-z0-9_.]+)\s*$', line)
        if m:
            cur = m.group(2) if m.group(1) == 'string' and m.group(2) in want else None
            continue
        if cur:
            m = re.match(r'\s+\(([^)]*)\)', line)
            if m:
                out.add(m.group(1))
    return sorted(out)


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace("'", "\\'")


def main():
    cfgs = configs()
    if not cfgs:
        raise SystemExit('no strings found in %s - is the path still right?' % APK)

    for d in os.listdir(OUT) if os.path.isdir(OUT) else []:
        if d == 'values' or d.startswith('values-'):
            shutil.rmtree(os.path.join(OUT, d))

    for cfg in cfgs:
        d = os.path.join(OUT, 'values' + ('-' + cfg if cfg else ''))
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, 'strings.xml'), 'w', encoding='utf-8') as fh:
            fh.write(HEADER)
            for n, v in STRINGS:
                fh.write('    <string name="%s">%s</string>\n' % (n, esc(v)))
            fh.write('</resources>\n')

    print('%d string(s) written for %d configuration(s): default + %s'
          % (len(STRINGS), len(cfgs), ', '.join(c for c in cfgs if c)))


main()
