#!/usr/bin/env python3
"""
Refits the BrinaOS wordmark vector into a target drawable's box.

Some of the logotypes an app ships are vectors whose intrinsic width and height
are part of the layout - the ImageView is wrap_content with centerInside, so a
replacement that changes the box changes the spacing around it. The wordmark
Brand.java produces has its own aspect (159.61 x 34), so it is centred inside a
viewport stretched to the target's aspect rather than being scaled to fill it,
which would squash the letterforms.

    python3 devices/common/rro/tools/padvec.py <src.xml> <wDp> <hDp> <#AARRGGBB> <out.xml>
"""
import re, sys

src, w_dp, h_dp, colour, out = sys.argv[1], float(sys.argv[2]), float(sys.argv[3]), sys.argv[4], sys.argv[5]
text = open(src, encoding='utf-8').read()


def attr(name):
    m = re.search(r'android:%s="([^"]*)"' % name, text)
    if not m:
        raise SystemExit('%s has no android:%s' % (src, name))
    return m.group(1)


vw, vh = float(attr('viewportWidth')), float(attr('viewportHeight'))
path = re.search(r'android:pathData="([^"]*)"', text).group(1)

# keep the ink's own aspect: widen the viewport to the target box's aspect and
# centre the wordmark in it
box_vw = vh * (w_dp / h_dp)
if box_vw < vw:                      # target box is narrower than the wordmark
    box_vw, vh = vw, vw * (h_dp / w_dp)
dx = (box_vw - vw) / 2
dy = (vh - float(attr('viewportHeight'))) / 2

with open(out, 'w', encoding='utf-8') as fh:
    fh.write('<?xml version="1.0" encoding="utf-8"?>\n')
    fh.write('<!-- Generated by devices/common/rro/tools/padvec.py from %s - do not hand edit.\n'
             '     The wordmark centred in a %gx%gdp box so the stock intrinsic size,\n'
             '     and with it the layout around the ImageView, is unchanged. -->\n'
             % (src.split('/')[-1], w_dp, h_dp))
    fh.write('<vector xmlns:android="http://schemas.android.com/apk/res/android"\n')
    fh.write('    android:width="%gdp"\n    android:height="%gdp"\n' % (w_dp, h_dp))
    fh.write('    android:viewportWidth="%.2f"\n    android:viewportHeight="%.2f">\n' % (box_vw, vh))
    fh.write('    <group android:translateX="%.2f" android:translateY="%.2f">\n' % (dx, dy))
    fh.write('        <path\n            android:fillColor="%s"\n' % colour)
    fh.write('            android:fillType="evenOdd"\n')
    fh.write('            android:pathData="%s" />\n' % path)
    fh.write('    </group>\n</vector>\n')

print('wrote %s  box %gx%gdp, viewport %.2fx%.2f, wordmark offset %.2f,%.2f'
      % (out, w_dp, h_dp, box_vw, vh, dx, dy))
